name: Legacy - step 1. Build OpenWrt toolchain cache

on:
  workflow_dispatch:
    inputs:
      openwrt_version:
        description: "OpenWrt version"
        type: string
        required: true
        default: "SNAPSHOT"
      amneziawg_version:
        description: "AmneziaWG version"
        type: string
        required: true
        default: "master"
      openwrt_arch:
        description: "OpenWrt arch"
        type: string
        required: true
        default: "aarch64_cortex-a53"
      openwrt_target:
        description: "OpenWrt target"
        type: string
        required: true
        default: "mediatek"
      openwrt_subtarget:
        description: "OpenWrt subtarget"
        type: string
        required: true
        default: "filogic"
      update_go:
        description: "Update Go version"
        type: boolean
        required: true
        default: true

jobs:
  build-toolchain-cache:
    name: "Build AmneziaWG packages for OpenWrt: ${{ inputs.openwrt_version }} - ${{ inputs.openwrt_arch }} - ${{ inputs.openwrt_target }}/${{ inputs.openwrt_subtarget }}"
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Install additional packages
        run: |
          set -e -x
          sudo apt-get update
          sudo apt-get install -y python3-pyelftools python3-dev python3-setuptools swig    

      - name: Checkout YAAWG repository
        uses: actions/checkout@v5
        with:
          path: amneziawg
          ref: ${{ inputs.amneziawg_version }}
          fetch-depth: 0

      - name: Checkout OpenWrt repository
        uses: actions/checkout@v5
        with:
          path: openwrt
          repository: openwrt/openwrt
          ref: ${{ inputs.openwrt_version == 'SNAPSHOT' && 'master' || format('v{0}', inputs.openwrt_version) }}
          fetch-depth: 0

      - name: Checkout OpenWRT Packages repository
        uses: actions/checkout@v5
        if: ${{ inputs.update_go }}
        with:
          path: packages
          repository: openwrt/packages
          fetch-depth: 0

      - name: Update feeds
        run: |
          set -e -x
          cd openwrt
          echo "src-cpy awgopenwrt ../amneziawg" >> feeds.conf.default
          ./scripts/feeds update -a
          if [ "${{ inputs.openwrt_version }}" = "SNAPSHOT" ]; then
            base_url="https://downloads.openwrt.org/snapshots/targets/${{ inputs.openwrt_target }}/${{ inputs.openwrt_subtarget }}"
          else
            base_url="https://downloads.openwrt.org/releases/${{ inputs.openwrt_version }}/targets/${{ inputs.openwrt_target }}/${{ inputs.openwrt_subtarget }}"
          fi
          curl -fsL "$base_url/config.buildinfo" > .config
          echo "CONFIG_PACKAGE_kmod-crypto-lib-chacha20=y" >> .config
          echo "CONFIG_PACKAGE_kmod-crypto-lib-chacha20poly1305=y" >> .config
          echo "CONFIG_PACKAGE_kmod-crypto-chacha20poly1305=y" >> .config
          echo "CONFIG_PACKAGE_kmod-amneziawg=y" >> .config
          echo "CONFIG_PACKAGE_amneziawg-go=y" >> .config
          echo "CONFIG_PACKAGE_amneziawg-tools=y" >> .config
          echo "CONFIG_PACKAGE_luci-proto-amneziawg=y" >> .config

      - name: Update Go version
        if: ${{ inputs.update_go }}
        run: |
          set -e -x
          rm -r openwrt/feeds/packages/lang/golang
          cp -r packages/lang/golang openwrt/feeds/packages/lang

      - name: Build toolchain and kernel
        run: |
          set -e -x
          cd openwrt
          ./scripts/feeds install -a
          make defconfig
          make tools/install -j $(nproc)
          make toolchain/install -j $(nproc)
          make target/linux/compile -j $(nproc)
          export LC_ALL=C
          for deadlink in $(find . -follow -type l -printf "" 2>&1 | sed -e "s/find: '\(.*\)': Too many levels of symbolic links.*/\1/"); do
            echo "Deleting dead link: ${deadlink}"
            rm -f "${deadlink}"
          done

      - name: Save toolchain and kernel cache
        id: cache-tools-kernel-save
        uses: actions/cache/save@v4
        with:
          key: ${{ runner.os }}-openwrt-cache-toolchain-kernel-${{ inputs.openwrt_version }}-${{ inputs.openwrt_arch }}-${{ inputs.openwrt_target }}-${{ inputs.openwrt_subtarget }}
          path: |
            openwrt/.config
            openwrt/.config.old
            openwrt/feeds.conf.default
            openwrt/bin/**
            openwrt/build_dir/**
            openwrt/dl/**
            openwrt/feeds/**
            openwrt/package/**
            openwrt/staging_dir/**
            openwrt/tmp/**
